// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjjjwtqrlpdndsesylko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqamp3dHFybHBkbmRzZXN5bGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NTY5ODQsImV4cCI6MjA1NDMzMjk4NH0.fRDOncvJWNDQKF2xHaRuv0PSvpe-OEpxkQbipOfkH_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);